// <auto-generated>
//     Generated by the DISetup template. Do not edit — regenerated on every run.
//     Contributes registrations for types this class does not own.
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace XpEng.Coder80.Infrastructure;

/// <summary>
/// Registers types this class does not own — a scaffolded entity, a hand-written class,
/// anything a [Register] attribute cannot reach because the type cannot be decorated.
///
/// Any number of implementations may coexist, so several templates can contribute to
/// the same project independently. Registrations made here are VALIDATED: two sources
/// registering the same service type without declaring intent to override is an error.
/// To replace an existing registration deliberately, use IOverrideRegistrations.
///
/// Implementations need a public parameterless constructor.
/// </summary>
public interface IAddRegistrations {
    void AddRegistrations(IServiceCollection services);
}
