// <auto-generated>
//     Generated by the DesignTimeSetup template. Do not edit — regenerated on every run.
//     Sets the design-mode flag as this assembly loads.
// </auto-generated>

#nullable enable

using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows;
using XpEng.Coder80.Infrastructure.Services;

namespace XpEng.Coder03.Views;

internal static class DesignTimeModuleInitializer {

    /// <summary>
    /// Runs automatically as this assembly loads into any process — including the XAML
    /// designer's, which loads it to render but never runs application startup. That is
    /// why this is a module initializer rather than a call from App.xaml.cs.
    ///
    /// DesignerProperties is the reliable check; it needs PresentationFramework, which is
    /// why this lives here rather than alongside the flag it sets.
    /// </summary>
    [ModuleInitializer]
    internal static void Initialize() {
        DesignTimeDetector.IsInDesignMode = DesignerProperties.GetIsInDesignMode(new DependencyObject());
    }
}
