// <auto-generated>
//     Generated by the DesignTimeSetup template. Do not edit — regenerated on every run.
//     Resolves a singleton from the container, with a design-time fallback.
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace XpEng.Coder80.Infrastructure.Services;

/// <summary>
/// Resolves T from the container, falling back to a directly constructed instance when
/// the container is unavailable AND the process is the designer's.
///
/// The design-mode condition matters: a resolution failure in production or in a test
/// is a real bug and propagates. Only the designer — where the container genuinely was
/// never built — gets the fallback, so a view can still render.
///
/// A generic static class holds separate fields per closed type, so each singleton gets
/// its own fallback with no per-type code.
/// </summary>
public static class DesignTimeSingleton<T> where T : class {

    private static readonly Lock _lock = new();
    private static T? _designTimeFallback;

    public static T Resolve(Func<T> constructFallback) {
        try {
            return XpEng.Coder80.Infrastructure.ServiceLocator.CurrentProvider.GetRequiredService<T>();
        }
        catch {
            if (!DesignTimeDetector.IsInDesignMode) throw;

            lock (_lock) {
                return _designTimeFallback ??= constructFallback();
            }
        }
    }
}
