namespace XpEng.Coder06.ViewModels {
    // ReSharper disable once InconsistentNaming
    public static class UIConstants {
        // Default path constants (kept as contingency, but ignored by the UI if JSON is empty)
        public const string DefaultSourcePath = @"C:\Users\julio\source\repos\JullioSanntos\Temp\TBQuiz.App\TBQuiz\TBQuiz06.Data\Models";
        public const string DefaultTargetPath = @"C:\Users\julio\source\repos\JullioSanntos\Temp\TBQuiz.App\TBQuiz\TBQuiz06.ViewModels\AutoGenerated";
        public const string DefaultTemplatePath = @"";

        public const string SourceFolderLabel = "Source Project Directory:";
        public const string TargetFolderLabel = "Target Output Directory:";
        public const string BrowseAction = "Browse...";

        public const string StartWatchingAction = "Start Monitoring";
        public const string StopWatchingAction = "Stop Monitoring";
        public const string ForceSyncAction = "Force Full Sync";
        public const string LogsLabel = "Engine Logs:";
        public const string SystemOfflineMsg = "System offline.";

        // Updated to reflect the new 3-path requirement
        public const string ErrorMissingPathsMsg = "Error: Source, Target, and Template paths must be set.";
    }
}