<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<!-- Add this line to enable the field keyword -->
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyVersion>1.2.0.0</AssemblyVersion>
		<FileVersion>1.2.0.0</FileVersion>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
    <InternalsVisibleTo Include="XpEng.Coder90.Tests" />
	</ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\XpEng.Coder09.Models\XpEng.Coder09.Models.csproj" />
    <ProjectReference Include="..\XpEng.Coder12.Services\XpEng.Coder12.Services.csproj" />
    <ProjectReference Include="..\XpEng.Coder80.Infrastructure\XpEng.Coder80.Infrastructure.csproj" />
  </ItemGroup>

</Project>
