using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace XpEng.Coder12.Services {

    public class CodeGenerator : ICodeGenerator {
        public void FullSynchronization(string dataProjectDir, string targetDir, Action<string> logAction) {
            logAction("[Sync] Performing Full Synchronization (File-to-File mapping)...");

            string generatedFolder = Path.Combine(targetDir, "AutoGenerated");
            if (Directory.Exists(generatedFolder)) {
                Directory.Delete(generatedFolder, true);
            }
            Directory.CreateDirectory(generatedFolder);

            var csFiles = Directory.GetFiles(dataProjectDir, "*.cs", SearchOption.AllDirectories);

            foreach (var file in csFiles) {
                SyncFile(file, generatedFolder, logAction);
            }

            UpdateMetadataJson(targetDir, logAction);
            logAction($"[Sync] Complete. Processed {csFiles.Length} files.");
            logAction(new string('-', 50));
        }

        public void ProcessBatch(IEnumerable<FileChangeEvent> changes, string dataProjectDir, string targetDir, Action<string> logAction) {
            logAction("Processing batched changes (File-to-File)...");

            string generatedFolder = Path.Combine(targetDir, "AutoGenerated");
            Directory.CreateDirectory(generatedFolder);
            foreach (var change in changes) {
                logAction($"   -> {change.ChangeType}: {Path.GetFileName(change.FullPath)}");

                string sourceFileName = Path.GetFileNameWithoutExtension(change.FullPath);

                if (change.ChangeType == ChangeType.Deleted) {
                    DeleteGeneratedFile(sourceFileName, generatedFolder, logAction);
                }
                else if (change.ChangeType == ChangeType.Renamed) {
                    if (!string.IsNullOrWhiteSpace(change.OldFullPath)) {
                        string oldFileName = Path.GetFileNameWithoutExtension(change.OldFullPath);
                        DeleteGeneratedFile(oldFileName, generatedFolder, logAction);
                    }
                    SyncFile(change.FullPath, generatedFolder, logAction);
                }
                else if (change.ChangeType == ChangeType.Created || change.ChangeType == ChangeType.Changed) {
                    SyncFile(change.FullPath, generatedFolder, logAction);
                }
            }

            UpdateMetadataJson(targetDir, logAction);

            logAction("Batch complete.");
            logAction(new string('-', 50));
        }

        private void SyncFile(string sourceFilePath, string generatedFolder, Action<string> logAction) {
            if (!File.Exists(sourceFilePath)) return;

            string fileName = Path.GetFileNameWithoutExtension(sourceFilePath);
            string generatedFilePath = Path.Combine(generatedFolder, $"{fileName}ViewModel.cs");

            // Use Roslyn to figure out the payload
            string code = File.ReadAllText(sourceFilePath);
            var syntaxTree = CSharpSyntaxTree.ParseText(code);
            var root = syntaxTree.GetCompilationUnitRoot();

            var classNames = root.DescendantNodes()
                                 .OfType<ClassDeclarationSyntax>()
                                 .Select(c => c.Identifier.Text)
                                 .ToList();

            // Generate a single file containing all classes found in the source file
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was generated by the XpEng Coder.");
            sb.AppendLine("// Do not edit this file directly.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace TBQuiz06.ViewModels.CGTypes");
            sb.AppendLine("{");

            foreach (var className in classNames) {
                sb.AppendLine($"    public partial class {className}ViewModel");
                sb.AppendLine("    {");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            File.WriteAllText(generatedFilePath, sb.ToString());
            logAction($"      [+] Synced: {fileName}ViewModel.cs ({classNames.Count} classes)");
        }

        private void DeleteGeneratedFile(string sourceFileName, string generatedFolder, Action<string> logAction) {
            string targetFilePath = Path.Combine(generatedFolder, $"{sourceFileName}ViewModel.cs");
            if (File.Exists(targetFilePath)) {
                File.Delete(targetFilePath);
                logAction($"      [-] Deleted: {sourceFileName}ViewModel.cs");
            }
        }

        private void UpdateMetadataJson(string targetDir, Action<string> logAction) {
            // Statelessly rebuild the JSON by parsing the actual physical output directory
            string generatedFolder = Path.Combine(targetDir, "AutoGenerated");
            var generatedFiles = Directory.Exists(generatedFolder)
                ? Directory.GetFiles(generatedFolder, "*ViewModel.cs")
                : Array.Empty<string>();

            var classNames = new List<string>();

            foreach (var file in generatedFiles) {
                string code = File.ReadAllText(file);
                var syntaxTree = CSharpSyntaxTree.ParseText(code);
                var root = syntaxTree.GetCompilationUnitRoot();

                var viewModels = root.DescendantNodes()
                                     .OfType<ClassDeclarationSyntax>()
                                     .Select(c => c.Identifier.Text);

                foreach (var vm in viewModels) {
                    if (vm.EndsWith("ViewModel")) {
                        classNames.Add(vm.Substring(0, vm.Length - 9)); // Strip "ViewModel" for the JSON
                    }
                }
            }

            var jsonBuilder = new StringBuilder();
            jsonBuilder.AppendLine("{");
            jsonBuilder.AppendLine("  \"Classes\": [");

            for (int i = 0; i < classNames.Count; i++) {
                jsonBuilder.Append($"    {{ \"Name\": \"{classNames[i]}\" }}");
                if (i < classNames.Count - 1)
                    jsonBuilder.AppendLine(",");
                else
                    jsonBuilder.AppendLine();
            }

            jsonBuilder.AppendLine("  ]");
            jsonBuilder.AppendLine("}");

            string jsonPath = Path.Combine(targetDir, "SyntaxMetadata.json");
            File.WriteAllText(jsonPath, jsonBuilder.ToString());

            logAction("      [~] SyntaxMetadata.json updated.");
        }
    }
}