using System.Text;

namespace XpEng.Coder80.Infrastructure.Services;

/// <summary>
/// Locates and writes the per-invocation argument and log files that let a T4 template
/// run under any host — Coder.App or a manual Visual Studio invocation.
///
/// Files live flat in {SolutionRoot}\CoderTemplates\ and are named for the template plus
/// the target directory relative to the solution root, so two invocations of the same
/// template against different targets cannot overwrite each other.
/// </summary>
public static class TemplateArgumentsFile {

    public const string FolderName = "CoderTemplates";

    /// <summary>The CoderTemplates folder beside the solution file, created if absent.</summary>
    public static string GetFolder(string solutionFilePath) {
        string solutionRoot = Path.GetDirectoryName(Path.GetFullPath(solutionFilePath))
                              ?? throw new ArgumentException("Could not determine the solution folder.", nameof(solutionFilePath));

        string folder = Path.Combine(solutionRoot, FolderName);
        Directory.CreateDirectory(folder);
        return folder;
    }

    /// <summary>
    /// Base file name for one invocation: the template name, plus the target directory
    /// relative to the solution root with separators flattened to underscores. Setup has no
    /// target directory, so its base name is just the template name.
    /// </summary>
    public static string BuildBaseName(string templatePath, string solutionFilePath, string? targetDirectory) {
        string templateName = Path.GetFileNameWithoutExtension(templatePath);
        if (string.IsNullOrWhiteSpace(targetDirectory)) return templateName;

        string solutionRoot = Path.GetDirectoryName(Path.GetFullPath(solutionFilePath)) ?? string.Empty;
        string relative = Path.GetRelativePath(solutionRoot, Path.GetFullPath(targetDirectory));

        // A target outside the solution tree has no meaningful relative form; fall back to
        // its leaf folder rather than emitting a name full of ".." segments.
        if (relative.StartsWith("..", StringComparison.Ordinal)) relative = Path.GetFileName(targetDirectory.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));

        string flattened = relative
            .Replace(Path.DirectorySeparatorChar, '_')
            .Replace(Path.AltDirectorySeparatorChar, '_')
            .Trim('_');

        return string.IsNullOrWhiteSpace(flattened) ? templateName : $"{templateName}_{flattened}";
    }

    public static string GetArgumentsFilePath(string templatePath, string solutionFilePath, string? targetDirectory = null) =>
        Path.Combine(GetFolder(solutionFilePath), $"{BuildBaseName(templatePath, solutionFilePath, targetDirectory)}.args.txt");

    public static string GetLogFilePath(string templatePath, string solutionFilePath, string? targetDirectory = null) =>
        Path.Combine(GetFolder(solutionFilePath), $"{BuildBaseName(templatePath, solutionFilePath, targetDirectory)}.log.txt");

    /// <summary>
    /// Writes the arguments file, overwriting unconditionally — it records what ran, so a
    /// hand-edited file is expected to be replaced on the next Coder.App invocation.
    /// </summary>
    public static string Write(string templatePath, string solutionFilePath, IDictionary<string, string> arguments, string? targetDirectory = null) {
        string path = GetArgumentsFilePath(templatePath, solutionFilePath, targetDirectory);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Coder.App. Overwritten on every invocation.");
        sb.AppendLine("# Edit freely for a manual run; the next Coder.App run will replace it.");
        sb.AppendLine($"# Template : {templatePath}");
        sb.AppendLine($"# Written  : {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        foreach (var pair in arguments.OrderBy(a => a.Key, StringComparer.OrdinalIgnoreCase))
            sb.AppendLine($"{pair.Key}={pair.Value}");

        File.WriteAllText(path, sb.ToString());
        return path;
    }

    /// <summary>Reads a key=value file, ignoring blank lines and # comments.</summary>
    public static Dictionary<string, string> Read(string argumentsFilePath) {
        var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (!File.Exists(argumentsFilePath)) return result;

        foreach (string rawLine in File.ReadAllLines(argumentsFilePath)) {
            string line = rawLine.Trim();
            if (line.Length == 0 || line.StartsWith('#')) continue;

            int separator = line.IndexOf('=');
            if (separator <= 0) continue;

            result[line[..separator].Trim()] = line[(separator + 1)..].Trim();
        }
        return result;
    }
}